environment:
  name: dev
  project: cdf-bootcamp-03-test # Your CDF project
  type: dev #prod, staging or dev
  selected:
    - modules/data_foundation
    - modules/ice_cream_api
    - modules/uc_oee

variables:
  CDF_PROJECT: cdf-bootcamp-03-test
  IDP_CLIENT_ID: ${IDP_CLIENT_ID}
  IDP_CLIENT_SECRET: ${IDP_CLIENT_SECRET}
  IDP_TENANT_ID: 16e3985b-ebe8-4e24-9da4-933e21a9fc81 # Since we all have the same tenant, this number does not change
  CDF_URL: https://westeurope-1.cognitedata.com # This is related to the cluster where the CDF project is hosted.
  IDP_SCOPES: https://westeurope-1.cognitedata.com/.default

  # Groups
  data_developer_source_id: 72842903-e4b4-4cd5-80a6-3a3abfcc3d4b
  oee_data_pipeline_source_id: e377006b-8e13-4f38-8d6b-c07be5d5c793
  readwrite_source_id: b7b46ae1-f383-478f-bf47-f9972cc69e02
  readonly_source_id: 4c0f8010-bd87-4cf1-8e88-49d54022b55a
  icapi_extractors_source_id: ed0e516d-d986-4ca9-90ee-a884a4aca040

  # Client Ids
  sp_oee_client_id: 70716e19-cd2d-41c1-97c8-31db114a6eb0
  sp_oee_client_secret: ${IDP_CLIENT_SECRET}
  icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
  icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}

  modules:
    icapi_ds_external_id: ds_ice_cream_api
    uc_oee_ds_external_id: ds_uc_oee
